#!/usr/bin/env bash

#####################################################################
#  Copyright (c) 2020, AJXS.
#  This program is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by the
#  Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  Authors:
#     Anthony <ajxs [at] panoptic.online>
#####################################################################

db_host="localhost"
db_port=54327
db_user="webmaster"
db_pass="pw"
db_name="webring_dev"

# The database connection string.
connection_string="postgresql://${db_user}:${db_pass}@${db_host}:${db_port}/${db_name}"
# The current working directory.
# This allows the script to be invoked via the makefile without any issues.
current_working_directory="$(dirname "${0}")"


echo ""
echo "░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░"
echo "░             Webri.ng Database Setup               ░"
echo "░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░"
echo ""

echo "Creating database schema"
psql --quiet --no-password "${connection_string}" -f "${current_working_directory}/schema.sql" || exit 1

echo "Creating database schema"
psql --quiet --no-password "${connection_string}" -f "${current_working_directory}/app_user.sql" || exit 1
