#!/usr/bin/env bash

#####################################################################
#  Copyright (c) 2020, AJXS.
#  This program is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by the
#  Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  Authors:
#     Anthony <ajxs [at] panoptic.online>
#####################################################################

# Set these variables if they aren't already set in the environment.
: ${DB_HOST="localhost"}
: ${DB_PORT=54327}
: ${DB_USER="webmaster"}
: ${DB_PASS="pw"}
: ${DB_NAME="webring_dev"}

# The database connection string.
connection_string="postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
# The current working directory.
# This allows the script to be invoked via the makefile without any issues.
current_working_directory="$(dirname "${0}")"


echo ""
echo "░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░"
echo "░             Webri.ng Database Setup               ░"
echo "░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░"
echo ""

echo "Creating database schema"
psql --quiet --no-password "${connection_string}" -f "${current_working_directory}/schema.sql" || exit 1

echo "Creating database user"
psql --quiet --no-password "${connection_string}" -f "${current_working_directory}/app_user.sql" || exit 1
